# config.yaml

backtest:
  # Define the date range for the backtest
  start_date: "2025-09-02"
  end_date: "2025-09-03"

  # Define the symbols to backtest
  symbols:
    - "NSE:SBIN-EQ"
    - "NSE:RELIANCE-EQ"
    - "NSE:HDFCBANK-EQ"

  # Define the strategy and its parameters
  strategy:
    name: "SMACrossoverStrategy"
    resolution: "1"
    params:
      short_window: 9
      long_window: 21
      trade_quantity: 100

  # Set the initial portfolio cash
  initial_cash: 1000000.0
