paper_trade_type: Positional
params:
  trade_value: 100000
strategy: opening_price_crossover
timeframes:
- '15'
- '30'
symbols:
- NSE:HDFCBANK-EQ
- NSE:ICICIBANK-EQ
- NSE:RELIANCE-EQ
- NSE:INFY-EQ
- NSE:BHARTIARTL-EQ
- NSE:LT-EQ
- NSE:ITC-EQ
- NSE:TCS-EQ
- NSE:SBIN-EQ
- NSE:AXISBANK-EQ
- NSE:M&M-EQ
- NSE:KOTAKBANK-EQ
- NSE:BAJFINANCE-EQ
- NSE:HINDUNILVR-EQ
- NSE:ETERNAL-EQ
- NSE:MARUTI-EQ
- NSE:SUNPHARMA-EQ
- NSE:NTPC-EQ
- NSE:HCLTECH-EQ
- NSE:TATAMOTORS-EQ
- NSE:ULTRACEMCO-EQ
- NSE:TITAN-EQ
- NSE:BEL-EQ
- NSE:TATASTEEL-EQ
- NSE:POWERGRID-EQ
- NSE:TRENT-EQ
- NSE:ASIANPAINT-EQ
- NSE:BAJAJFINSV-EQ
- NSE:HINDALCO-EQ
- NSE:GRASIM-EQ
- NSE:JSWSTEEL-EQ
- NSE:JIOFIN-EQ
- NSE:ADANIPORTS-EQ
- NSE:BAJAJ-AUTO-EQ
- NSE:TECHM-EQ
- NSE:EICHERMOT-EQ
- NSE:ONGC-EQ
- NSE:COALINDIA-EQ
- NSE:SHRIRAMFIN-EQ
- NSE:CIPLA-EQ
- NSE:NESTLEIND-EQ
- NSE:HDFCLIFE-EQ
- NSE:SBILIFE-EQ
- NSE:DRREDDY-EQ
- NSE:APOLLOHOSP-EQ
- NSE:TATACONSUM-EQ
- NSE:WIPRO-EQ
- NSE:HEROMOTOCO-EQ
- NSE:ADANIENT-EQ
- NSE:INDUSINDBK-EQ
