paper_trade_type: Intraday
params:
  trade_value: 100000
strategy: Opening Price Crossover
symbols:
- NSE:NIFTY25SEP25000CE
- NSE:NIFTY25SEP25000PE
- NSE:BANKNIFTY25SEP54700CE
- NSE:BANKNIFTY25SEP54700PE
- BSE:SENSEX25SEP81500CE
- BSE:SENSEX25SEP81500PE
- BSE:BANKEX25SEP61200CE
- BSE:BANKEX25SEP61200PE
